name: 'Helm Chart Publish'
description: 'Bash Wrapper for Chart Releaser with improved functionality'
author: 'oliverbaehler'
branding:
  icon: 'archive'
  color: 'purple'
inputs:

  ## Configuration for the personal acces token being used
  ##
  token:
    description: 'A personal access token needed to push your site after it has been built.'
    required: true

  ## Configuration fo a Chart Releaser COnfiguration
  ##
  config:
    description: 'Chart Releaser configuration file'
    required: false
    default: './cr.yaml'

  ## Chart Configuration filename
  ##
  chartConfig:
    description: 'Chart Configuration file'
    required: false


  ## Configuration for the git username (Release owner)
  ##
  user:
    description: 'Define the user name used for commits (pages update)'
    required: false

  ## Configuration for the git email
  ##
  email:
    description: 'Define the user email used for commits (pages update)'
    required: false

  ## Configuration for git-repo name
  ## Reference: https://github.com/helm/chart-releaser#environment-variables
  ##
  repository:
    description: 'Define the repository url, where the index is exposed. By default we assume you are using {org/user}.github.io/{repo-name}/'
    required: false

  ## Configuration for charts directories
  ##
  chartRoot:
    description: 'Charts root directory'
    default: 'charts/'
    required: false

  ## Auto Generate Schema File
  ## If no schema is present, the schema is generated automaticaly
  ## Reference: https://github.com/karuppiah7890/helm-schema-gen
  ##
  schema:
    description: 'Auto generate chart schema'
    required: false

runs:
  using: docker
  image: Dockerfile
