name: 'Helm Chart Publish'
description: 'Bash Wrapper for Chart Releaser with improved functionality'
author: 'oliverbaehler'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  exec:
    description: 'Declare which script to execute'
    required: false
  charts:
    description: 'Declare changed charts'
    required: false
  chartConfig:
    description: "Define filename for chart configuration file"
    required: false 
    default: ".chart-config"  

runs:
  using: docker
  image: Dockerfile
