---
name: "Release"
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Stable Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  changelog:
    name: "Changelog"
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Changelog
        id: generate-changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Changelog
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -sam "Update Changelog"
          git push
